# Generated by Django 5.1.1 on 2024-09-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
