# Generated by Django 5.1.1 on 2024-09-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0002_inmueble_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='m2_construidos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='m2_totales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='num_baños',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='num_estacionamientos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='num_habitaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio_ufs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
