# Generated by Django 3.2.4 on 2024-09-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
