# Generated by Django 5.1.1 on 2024-10-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0005_auto_20240909_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('dueño', 'Dueño'), ('cliente', 'Cliente')], default='cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
